/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Sat Apr 23 17:04:32 2016. */

#ifndef PB_DEVICECOMMANDS_PB_H_INCLUDED
#define PB_DEVICECOMMANDS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _DevicePortFeature {
    DevicePortFeature_SWITCH = 0,
    DevicePortFeature_IR = 1
} DevicePortFeature;

/* Struct definitions */
typedef struct _CommandAckResponse {
    int32_t message_id;
/* @@protoc_insertion_point(struct:CommandAckResponse) */
} CommandAckResponse;

typedef struct _DeviceConnectedEvent {
    char device_id[32];
/* @@protoc_insertion_point(struct:DeviceConnectedEvent) */
} DeviceConnectedEvent;

typedef struct _DeviceDisconnectedEvent {
    char device_id[32];
/* @@protoc_insertion_point(struct:DeviceDisconnectedEvent) */
} DeviceDisconnectedEvent;

typedef struct _DeviceHearbeatEvent {
    char device_id[32];
    int32_t sequence_id;
/* @@protoc_insertion_point(struct:DeviceHearbeatEvent) */
} DeviceHearbeatEvent;

typedef struct _DeviceHumidityMeasuredEvent {
    char device_id[32];
    int32_t port;
    float value;
/* @@protoc_insertion_point(struct:DeviceHumidityMeasuredEvent) */
} DeviceHumidityMeasuredEvent;

typedef struct _DeviceIRReceivedEvent {
    char device_id[32];
    int32_t port;
    uint32_t value;
/* @@protoc_insertion_point(struct:DeviceIRReceivedEvent) */
} DeviceIRReceivedEvent;

typedef struct _DeviceIRSendCommand {
    int32_t message_id;
    int32_t port;
    uint32_t value;
/* @@protoc_insertion_point(struct:DeviceIRSendCommand) */
} DeviceIRSendCommand;

typedef struct _DeviceMovementDetectedEvent {
    char device_id[32];
    int32_t port;
/* @@protoc_insertion_point(struct:DeviceMovementDetectedEvent) */
} DeviceMovementDetectedEvent;

typedef struct _DevicePort {
    int32_t port;
    bool has_description;
    char description[64];
    DevicePortFeature feature;
/* @@protoc_insertion_point(struct:DevicePort) */
} DevicePort;

typedef struct _DeviceSwitchCommand {
    int32_t message_id;
    int32_t port;
    bool on;
/* @@protoc_insertion_point(struct:DeviceSwitchCommand) */
} DeviceSwitchCommand;

typedef struct _DeviceTemperatureMeasuredEvent {
    char device_id[32];
    int32_t port;
    float value;
/* @@protoc_insertion_point(struct:DeviceTemperatureMeasuredEvent) */
} DeviceTemperatureMeasuredEvent;

typedef struct _DeviceDescription {
    char device_id[32];
    pb_size_t ports_count;
    DevicePort ports[16];
/* @@protoc_insertion_point(struct:DeviceDescription) */
} DeviceDescription;

typedef struct _DeviceEvents {
    bool has_deviceConnectedEvent;
    DeviceConnectedEvent deviceConnectedEvent;
    bool has_deviceHearbeatEvent;
    DeviceHearbeatEvent deviceHearbeatEvent;
    bool has_deviceDisconnectedEvent;
    DeviceDisconnectedEvent deviceDisconnectedEvent;
    bool has_temperatureMeasureEvent;
    DeviceTemperatureMeasuredEvent temperatureMeasureEvent;
    bool has_humidityMeasureEvent;
    DeviceHumidityMeasuredEvent humidityMeasureEvent;
    bool has_movementDetectionEvent;
    DeviceMovementDetectedEvent movementDetectionEvent;
    bool has_irReceivedEvent;
    DeviceIRReceivedEvent irReceivedEvent;
/* @@protoc_insertion_point(struct:DeviceEvents) */
} DeviceEvents;

typedef struct _DeviceMessage {
    bool has_switchCommand;
    DeviceSwitchCommand switchCommand;
    bool has_irSendCommand;
    DeviceIRSendCommand irSendCommand;
/* @@protoc_insertion_point(struct:DeviceMessage) */
} DeviceMessage;

/* Default values for struct fields */

/* Initializer values for message structs */
#define DevicePort_init_default                  {0, false, "", (DevicePortFeature)0}
#define DeviceDescription_init_default           {"", 0, {DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default, DevicePort_init_default}}
#define DeviceSwitchCommand_init_default         {0, 0, 0}
#define DeviceIRSendCommand_init_default         {0, 0, 0}
#define DeviceMessage_init_default               {false, DeviceSwitchCommand_init_default, false, DeviceIRSendCommand_init_default}
#define CommandAckResponse_init_default          {0}
#define DeviceConnectedEvent_init_default        {""}
#define DeviceDisconnectedEvent_init_default     {""}
#define DeviceHearbeatEvent_init_default         {"", 0}
#define DeviceTemperatureMeasuredEvent_init_default {"", 0, 0}
#define DeviceHumidityMeasuredEvent_init_default {"", 0, 0}
#define DeviceMovementDetectedEvent_init_default {"", 0}
#define DeviceIRReceivedEvent_init_default       {"", 0, 0}
#define DeviceEvents_init_default                {false, DeviceConnectedEvent_init_default, false, DeviceHearbeatEvent_init_default, false, DeviceDisconnectedEvent_init_default, false, DeviceTemperatureMeasuredEvent_init_default, false, DeviceHumidityMeasuredEvent_init_default, false, DeviceMovementDetectedEvent_init_default, false, DeviceIRReceivedEvent_init_default}
#define DevicePort_init_zero                     {0, false, "", (DevicePortFeature)0}
#define DeviceDescription_init_zero              {"", 0, {DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero, DevicePort_init_zero}}
#define DeviceSwitchCommand_init_zero            {0, 0, 0}
#define DeviceIRSendCommand_init_zero            {0, 0, 0}
#define DeviceMessage_init_zero                  {false, DeviceSwitchCommand_init_zero, false, DeviceIRSendCommand_init_zero}
#define CommandAckResponse_init_zero             {0}
#define DeviceConnectedEvent_init_zero           {""}
#define DeviceDisconnectedEvent_init_zero        {""}
#define DeviceHearbeatEvent_init_zero            {"", 0}
#define DeviceTemperatureMeasuredEvent_init_zero {"", 0, 0}
#define DeviceHumidityMeasuredEvent_init_zero    {"", 0, 0}
#define DeviceMovementDetectedEvent_init_zero    {"", 0}
#define DeviceIRReceivedEvent_init_zero          {"", 0, 0}
#define DeviceEvents_init_zero                   {false, DeviceConnectedEvent_init_zero, false, DeviceHearbeatEvent_init_zero, false, DeviceDisconnectedEvent_init_zero, false, DeviceTemperatureMeasuredEvent_init_zero, false, DeviceHumidityMeasuredEvent_init_zero, false, DeviceMovementDetectedEvent_init_zero, false, DeviceIRReceivedEvent_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define CommandAckResponse_message_id_tag        1
#define DeviceConnectedEvent_device_id_tag       1
#define DeviceDisconnectedEvent_device_id_tag    1
#define DeviceHearbeatEvent_device_id_tag        1
#define DeviceHearbeatEvent_sequence_id_tag      2
#define DeviceHumidityMeasuredEvent_device_id_tag 1
#define DeviceHumidityMeasuredEvent_port_tag     2
#define DeviceHumidityMeasuredEvent_value_tag    3
#define DeviceIRReceivedEvent_device_id_tag      1
#define DeviceIRReceivedEvent_port_tag           2
#define DeviceIRReceivedEvent_value_tag          3
#define DeviceIRSendCommand_message_id_tag       1
#define DeviceIRSendCommand_port_tag             2
#define DeviceIRSendCommand_value_tag            3
#define DeviceMovementDetectedEvent_device_id_tag 1
#define DeviceMovementDetectedEvent_port_tag     2
#define DevicePort_port_tag                      1
#define DevicePort_description_tag               2
#define DevicePort_feature_tag                   3
#define DeviceSwitchCommand_message_id_tag       1
#define DeviceSwitchCommand_port_tag             2
#define DeviceSwitchCommand_on_tag               3
#define DeviceTemperatureMeasuredEvent_device_id_tag 1
#define DeviceTemperatureMeasuredEvent_port_tag  2
#define DeviceTemperatureMeasuredEvent_value_tag 3
#define DeviceDescription_device_id_tag          1
#define DeviceDescription_ports_tag              2
#define DeviceEvents_deviceConnectedEvent_tag    1
#define DeviceEvents_deviceHearbeatEvent_tag     2
#define DeviceEvents_deviceDisconnectedEvent_tag 3
#define DeviceEvents_temperatureMeasureEvent_tag 4
#define DeviceEvents_humidityMeasureEvent_tag    5
#define DeviceEvents_movementDetectionEvent_tag  6
#define DeviceEvents_irReceivedEvent_tag         7
#define DeviceMessage_switchCommand_tag          1
#define DeviceMessage_irSendCommand_tag          2

/* Struct field encoding specification for nanopb */
extern const pb_field_t DevicePort_fields[4];
extern const pb_field_t DeviceDescription_fields[3];
extern const pb_field_t DeviceSwitchCommand_fields[4];
extern const pb_field_t DeviceIRSendCommand_fields[4];
extern const pb_field_t DeviceMessage_fields[3];
extern const pb_field_t CommandAckResponse_fields[2];
extern const pb_field_t DeviceConnectedEvent_fields[2];
extern const pb_field_t DeviceDisconnectedEvent_fields[2];
extern const pb_field_t DeviceHearbeatEvent_fields[3];
extern const pb_field_t DeviceTemperatureMeasuredEvent_fields[4];
extern const pb_field_t DeviceHumidityMeasuredEvent_fields[4];
extern const pb_field_t DeviceMovementDetectedEvent_fields[3];
extern const pb_field_t DeviceIRReceivedEvent_fields[4];
extern const pb_field_t DeviceEvents_fields[8];

/* Maximum encoded size of messages (where known) */
#define DevicePort_size                          79
#define DeviceDescription_size                   1330
#define DeviceSwitchCommand_size                 24
#define DeviceIRSendCommand_size                 28
#define DeviceMessage_size                       56
#define CommandAckResponse_size                  11
#define DeviceConnectedEvent_size                34
#define DeviceDisconnectedEvent_size             34
#define DeviceHearbeatEvent_size                 45
#define DeviceTemperatureMeasuredEvent_size      50
#define DeviceHumidityMeasuredEvent_size         50
#define DeviceMovementDetectedEvent_size         45
#define DeviceIRReceivedEvent_size               51
#define DeviceEvents_size                        323

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEVICECOMMANDS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
