/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Mon Oct 17 21:25:51 2016. */

#include "DeviceCommands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DevicePort_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DevicePort, port, port, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, DevicePort, feature, port, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DevicePort, description, feature, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceDescription_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceDescription, device_id, device_id, 0),
    PB_FIELD(  2, MESSAGE , REPEATED, STATIC  , OTHER, DeviceDescription, ports, device_id, &DevicePort_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceSwitchCommand_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSwitchCommand, message_id, message_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceSwitchCommand, port, message_id, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, DeviceSwitchCommand, on, port, 0),
    PB_LAST_FIELD
};

const pb_field_t IRValue_fields[4] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, IRValue, format, format, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, IRValue, bits, format, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, IRValue, data, bits, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceIRSendCommand_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceIRSendCommand, message_id, message_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceIRSendCommand, port, message_id, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, DeviceIRSendCommand, value, port, &IRValue_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceMessage_fields[3] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, DeviceMessage, switchCommand, switchCommand, &DeviceSwitchCommand_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceMessage, irSendCommand, switchCommand, &DeviceIRSendCommand_fields),
    PB_LAST_FIELD
};

const pb_field_t UpgradeFirmwareCommand_fields[2] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, UpgradeFirmwareCommand, program_url, program_url, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceStatusRequest_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceStatusRequest, reply_to, reply_to, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceServiceCommand_fields[3] = {
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , FIRST, DeviceServiceCommand, upgradeFirmwareCommand, upgradeFirmwareCommand, &UpgradeFirmwareCommand_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceServiceCommand, statusRequest, upgradeFirmwareCommand, &DeviceStatusRequest_fields),
    PB_LAST_FIELD
};

const pb_field_t CommandAckResponse_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CommandAckResponse, message_id, message_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceConnectedEvent_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceConnectedEvent, device_id, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceDisconnectedEvent_fields[2] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceDisconnectedEvent, device_id, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceHearbeatEvent_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceHearbeatEvent, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceHearbeatEvent, sequence_id, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceUpgradedEvent_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceUpgradedEvent, device_id, device_id, 0),
    PB_FIELD(  2, BOOL    , REQUIRED, STATIC  , OTHER, DeviceUpgradedEvent, success, device_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DeviceUpgradedEvent, msg, success, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceStatusResponse_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceStatusResponse, device_id, device_id, 0),
    PB_FIELD(  2, STRING  , REQUIRED, STATIC  , OTHER, DeviceStatusResponse, message, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceUpgradeFailedEvent_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceUpgradeFailedEvent, device_id, device_id, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, DeviceUpgradeFailedEvent, msg, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceTemperatureMeasuredEvent_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceTemperatureMeasuredEvent, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceTemperatureMeasuredEvent, port, device_id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceTemperatureMeasuredEvent, value, port, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceHumidityMeasuredEvent_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceHumidityMeasuredEvent, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceHumidityMeasuredEvent, port, device_id, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, DeviceHumidityMeasuredEvent, value, port, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceMovementDetectedEvent_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceMovementDetectedEvent, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceMovementDetectedEvent, port, device_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceIRReceivedEvent_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, STATIC  , FIRST, DeviceIRReceivedEvent, device_id, device_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceIRReceivedEvent, port, device_id, 0),
    PB_FIELD(  3, MESSAGE , REQUIRED, STATIC  , OTHER, DeviceIRReceivedEvent, value, port, &IRValue_fields),
    PB_LAST_FIELD
};

const pb_field_t Responses_fields[2] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, Responses, deviceStatusResponse, deviceStatusResponse, &DeviceStatusResponse_fields),
    PB_LAST_FIELD
};

const pb_field_t DeviceEvents_fields[10] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, DeviceEvents, deviceConnectedEvent, deviceConnectedEvent, &DeviceConnectedEvent_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, deviceHearbeatEvent, deviceConnectedEvent, &DeviceHearbeatEvent_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, deviceDisconnectedEvent, deviceHearbeatEvent, &DeviceDisconnectedEvent_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, temperatureMeasureEvent, deviceDisconnectedEvent, &DeviceTemperatureMeasuredEvent_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, humidityMeasureEvent, temperatureMeasureEvent, &DeviceHumidityMeasuredEvent_fields),
    PB_FIELD(  6, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, movementDetectionEvent, humidityMeasureEvent, &DeviceMovementDetectedEvent_fields),
    PB_FIELD(  7, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, irReceivedEvent, movementDetectionEvent, &DeviceIRReceivedEvent_fields),
    PB_FIELD( 10, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, deviceUpgradedEvent, irReceivedEvent, &DeviceUpgradedEvent_fields),
    PB_FIELD( 11, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceEvents, deviceUpgradeFailedEvent, deviceUpgradedEvent, &DeviceUpgradeFailedEvent_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceDescription, ports[0]) < 65536 && pb_membersize(DeviceIRSendCommand, value) < 65536 && pb_membersize(DeviceMessage, switchCommand) < 65536 && pb_membersize(DeviceMessage, irSendCommand) < 65536 && pb_membersize(DeviceServiceCommand, upgradeFirmwareCommand) < 65536 && pb_membersize(DeviceServiceCommand, statusRequest) < 65536 && pb_membersize(DeviceIRReceivedEvent, value) < 65536 && pb_membersize(Responses, deviceStatusResponse) < 65536 && pb_membersize(DeviceEvents, deviceConnectedEvent) < 65536 && pb_membersize(DeviceEvents, deviceHearbeatEvent) < 65536 && pb_membersize(DeviceEvents, deviceDisconnectedEvent) < 65536 && pb_membersize(DeviceEvents, deviceUpgradedEvent) < 65536 && pb_membersize(DeviceEvents, deviceUpgradeFailedEvent) < 65536 && pb_membersize(DeviceEvents, temperatureMeasureEvent) < 65536 && pb_membersize(DeviceEvents, humidityMeasureEvent) < 65536 && pb_membersize(DeviceEvents, movementDetectionEvent) < 65536 && pb_membersize(DeviceEvents, irReceivedEvent) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DevicePort_DeviceDescription_DeviceSwitchCommand_IRValue_DeviceIRSendCommand_DeviceMessage_UpgradeFirmwareCommand_DeviceStatusRequest_DeviceServiceCommand_CommandAckResponse_DeviceConnectedEvent_DeviceDisconnectedEvent_DeviceHearbeatEvent_DeviceUpgradedEvent_DeviceStatusResponse_DeviceUpgradeFailedEvent_DeviceTemperatureMeasuredEvent_DeviceHumidityMeasuredEvent_DeviceMovementDetectedEvent_DeviceIRReceivedEvent_Responses_DeviceEvents)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceDescription, ports[0]) < 256 && pb_membersize(DeviceIRSendCommand, value) < 256 && pb_membersize(DeviceMessage, switchCommand) < 256 && pb_membersize(DeviceMessage, irSendCommand) < 256 && pb_membersize(DeviceServiceCommand, upgradeFirmwareCommand) < 256 && pb_membersize(DeviceServiceCommand, statusRequest) < 256 && pb_membersize(DeviceIRReceivedEvent, value) < 256 && pb_membersize(Responses, deviceStatusResponse) < 256 && pb_membersize(DeviceEvents, deviceConnectedEvent) < 256 && pb_membersize(DeviceEvents, deviceHearbeatEvent) < 256 && pb_membersize(DeviceEvents, deviceDisconnectedEvent) < 256 && pb_membersize(DeviceEvents, deviceUpgradedEvent) < 256 && pb_membersize(DeviceEvents, deviceUpgradeFailedEvent) < 256 && pb_membersize(DeviceEvents, temperatureMeasureEvent) < 256 && pb_membersize(DeviceEvents, humidityMeasureEvent) < 256 && pb_membersize(DeviceEvents, movementDetectionEvent) < 256 && pb_membersize(DeviceEvents, irReceivedEvent) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_DevicePort_DeviceDescription_DeviceSwitchCommand_IRValue_DeviceIRSendCommand_DeviceMessage_UpgradeFirmwareCommand_DeviceStatusRequest_DeviceServiceCommand_CommandAckResponse_DeviceConnectedEvent_DeviceDisconnectedEvent_DeviceHearbeatEvent_DeviceUpgradedEvent_DeviceStatusResponse_DeviceUpgradeFailedEvent_DeviceTemperatureMeasuredEvent_DeviceHumidityMeasuredEvent_DeviceMovementDetectedEvent_DeviceIRReceivedEvent_Responses_DeviceEvents)
#endif


/* @@protoc_insertion_point(eof) */
