/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Sat Apr 09 13:22:43 2016. */

#include "DeviceCommands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t DeviceSwitchCommand_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceSwitchCommand, message_id, message_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceSwitchCommand, port, message_id, 0),
    PB_FIELD(  3, BOOL    , REQUIRED, STATIC  , OTHER, DeviceSwitchCommand, on, port, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceIRCommand_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, DeviceIRCommand, message_id, message_id, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceIRCommand, port, message_id, 0),
    PB_FIELD(  3, BYTES   , REQUIRED, CALLBACK, OTHER, DeviceIRCommand, value, port, 0),
    PB_LAST_FIELD
};

const pb_field_t CommandAckResponse_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, CommandAckResponse, message_id, message_id, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceTemperatureMeasuredEvent_fields[4] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, DeviceTemperatureMeasuredEvent, device, device, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceTemperatureMeasuredEvent, port, device, 0),
    PB_FIELD(  3, SINT32  , REQUIRED, STATIC  , OTHER, DeviceTemperatureMeasuredEvent, value, port, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceMovementDetectedEvent_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, DeviceMovementDetectedEvent, device, device, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, DeviceMovementDetectedEvent, port, device, 0),
    PB_LAST_FIELD
};

const pb_field_t DeviceMessage_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, DeviceMessage, switchCommand, switchCommand, &DeviceSwitchCommand_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceMessage, irCommand, switchCommand, &DeviceIRCommand_fields),
    PB_FIELD( 32, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceMessage, ackResponse, irCommand, &CommandAckResponse_fields),
    PB_FIELD( 64, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceMessage, temperatureMeasureEvent, ackResponse, &DeviceTemperatureMeasuredEvent_fields),
    PB_FIELD( 65, MESSAGE , OPTIONAL, STATIC  , OTHER, DeviceMessage, movementDetectionEvent, temperatureMeasureEvent, &DeviceMovementDetectedEvent_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceMessage, switchCommand) < 65536 && pb_membersize(DeviceMessage, irCommand) < 65536 && pb_membersize(DeviceMessage, ackResponse) < 65536 && pb_membersize(DeviceMessage, temperatureMeasureEvent) < 65536 && pb_membersize(DeviceMessage, movementDetectionEvent) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_DeviceSwitchCommand_DeviceIRCommand_CommandAckResponse_DeviceTemperatureMeasuredEvent_DeviceMovementDetectedEvent_DeviceMessage)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(DeviceMessage, switchCommand) < 256 && pb_membersize(DeviceMessage, irCommand) < 256 && pb_membersize(DeviceMessage, ackResponse) < 256 && pb_membersize(DeviceMessage, temperatureMeasureEvent) < 256 && pb_membersize(DeviceMessage, movementDetectionEvent) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_DeviceSwitchCommand_DeviceIRCommand_CommandAckResponse_DeviceTemperatureMeasuredEvent_DeviceMovementDetectedEvent_DeviceMessage)
#endif


/* @@protoc_insertion_point(eof) */
