// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: nanopb.proto

package fi.kapsi.koti.jpa.nanopb;

public final class Nanopb {
  private Nanopb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbFileopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbMsgopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopbEnumopt);
    registry.add(fi.kapsi.koti.jpa.nanopb.Nanopb.nanopb);
  }
  /**
   * Protobuf enum {@code FieldType}
   */
  public enum FieldType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FT_DEFAULT = 0;</code>
     *
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     */
    FT_DEFAULT(0, 0),
    /**
     * <code>FT_CALLBACK = 1;</code>
     *
     * <pre>
     * Always generate a callback field.
     * </pre>
     */
    FT_CALLBACK(1, 1),
    /**
     * <code>FT_POINTER = 4;</code>
     *
     * <pre>
     * Always generate a dynamically allocated field.
     * </pre>
     */
    FT_POINTER(2, 4),
    /**
     * <code>FT_STATIC = 2;</code>
     *
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     */
    FT_STATIC(3, 2),
    /**
     * <code>FT_IGNORE = 3;</code>
     *
     * <pre>
     * Ignore the field completely.
     * </pre>
     */
    FT_IGNORE(4, 3),
    ;

    /**
     * <code>FT_DEFAULT = 0;</code>
     *
     * <pre>
     * Automatically decide field type, generate static field if possible.
     * </pre>
     */
    public static final int FT_DEFAULT_VALUE = 0;
    /**
     * <code>FT_CALLBACK = 1;</code>
     *
     * <pre>
     * Always generate a callback field.
     * </pre>
     */
    public static final int FT_CALLBACK_VALUE = 1;
    /**
     * <code>FT_POINTER = 4;</code>
     *
     * <pre>
     * Always generate a dynamically allocated field.
     * </pre>
     */
    public static final int FT_POINTER_VALUE = 4;
    /**
     * <code>FT_STATIC = 2;</code>
     *
     * <pre>
     * Generate a static field or raise an exception if not possible.
     * </pre>
     */
    public static final int FT_STATIC_VALUE = 2;
    /**
     * <code>FT_IGNORE = 3;</code>
     *
     * <pre>
     * Ignore the field completely.
     * </pre>
     */
    public static final int FT_IGNORE_VALUE = 3;


    public final int getNumber() { return value; }

    public static FieldType valueOf(int value) {
      switch (value) {
        case 0: return FT_DEFAULT;
        case 1: return FT_CALLBACK;
        case 4: return FT_POINTER;
        case 2: return FT_STATIC;
        case 3: return FT_IGNORE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<FieldType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FieldType>() {
            public FieldType findValueByNumber(int number) {
              return FieldType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor().getEnumTypes().get(0);
    }

    private static final FieldType[] VALUES = values();

    public static FieldType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private FieldType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FieldType)
  }

  /**
   * Protobuf enum {@code IntSize}
   */
  public enum IntSize
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IS_DEFAULT = 0;</code>
     *
     * <pre>
     * Default, 32/64bit based on type in .proto
     * </pre>
     */
    IS_DEFAULT(0, 0),
    /**
     * <code>IS_8 = 8;</code>
     */
    IS_8(1, 8),
    /**
     * <code>IS_16 = 16;</code>
     */
    IS_16(2, 16),
    /**
     * <code>IS_32 = 32;</code>
     */
    IS_32(3, 32),
    /**
     * <code>IS_64 = 64;</code>
     */
    IS_64(4, 64),
    ;

    /**
     * <code>IS_DEFAULT = 0;</code>
     *
     * <pre>
     * Default, 32/64bit based on type in .proto
     * </pre>
     */
    public static final int IS_DEFAULT_VALUE = 0;
    /**
     * <code>IS_8 = 8;</code>
     */
    public static final int IS_8_VALUE = 8;
    /**
     * <code>IS_16 = 16;</code>
     */
    public static final int IS_16_VALUE = 16;
    /**
     * <code>IS_32 = 32;</code>
     */
    public static final int IS_32_VALUE = 32;
    /**
     * <code>IS_64 = 64;</code>
     */
    public static final int IS_64_VALUE = 64;


    public final int getNumber() { return value; }

    public static IntSize valueOf(int value) {
      switch (value) {
        case 0: return IS_DEFAULT;
        case 8: return IS_8;
        case 16: return IS_16;
        case 32: return IS_32;
        case 64: return IS_64;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<IntSize>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<IntSize>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<IntSize>() {
            public IntSize findValueByNumber(int number) {
              return IntSize.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.getDescriptor().getEnumTypes().get(1);
    }

    private static final IntSize[] VALUES = values();

    public static IntSize valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private IntSize(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:IntSize)
  }

  public interface NanoPBOptionsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:NanoPBOptions)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    boolean hasMaxSize();
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    int getMaxSize();

    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    boolean hasMaxCount();
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    int getMaxCount();

    /**
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     *
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     */
    boolean hasIntSize();
    /**
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     *
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     */
    fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize();

    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType();

    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    boolean hasLongNames();
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    boolean getLongNames();

    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     */
    boolean hasPackedStruct();
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     */
    boolean getPackedStruct();

    /**
     * <code>optional bool packed_enum = 10 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     */
    boolean hasPackedEnum();
    /**
     * <code>optional bool packed_enum = 10 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     */
    boolean getPackedEnum();

    /**
     * <code>optional bool skip_message = 6 [default = false];</code>
     *
     * <pre>
     * Skip this message
     * </pre>
     */
    boolean hasSkipMessage();
    /**
     * <code>optional bool skip_message = 6 [default = false];</code>
     *
     * <pre>
     * Skip this message
     * </pre>
     */
    boolean getSkipMessage();

    /**
     * <code>optional bool no_unions = 8 [default = false];</code>
     *
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     */
    boolean hasNoUnions();
    /**
     * <code>optional bool no_unions = 8 [default = false];</code>
     *
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     */
    boolean getNoUnions();

    /**
     * <code>optional uint32 msgid = 9;</code>
     *
     * <pre>
     * integer type tag for a message
     * </pre>
     */
    boolean hasMsgid();
    /**
     * <code>optional uint32 msgid = 9;</code>
     *
     * <pre>
     * integer type tag for a message
     * </pre>
     */
    int getMsgid();

    /**
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     *
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     */
    boolean hasAnonymousOneof();
    /**
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     *
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     */
    boolean getAnonymousOneof();
  }
  /**
   * Protobuf type {@code NanoPBOptions}
   *
   * <pre>
   * This is the inner options message, which basically defines options for
   * a field. When it is used in message or file scope, it applies to all
   * fields.
   * </pre>
   */
  public static final class NanoPBOptions extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:NanoPBOptions)
      NanoPBOptionsOrBuilder {
    // Use NanoPBOptions.newBuilder() to construct.
    private NanoPBOptions(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private NanoPBOptions(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final NanoPBOptions defaultInstance;
    public static NanoPBOptions getDefaultInstance() {
      return defaultInstance;
    }

    public NanoPBOptions getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private NanoPBOptions(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              maxSize_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              maxCount_ = input.readInt32();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000008;
                type_ = value;
              }
              break;
            }
            case 32: {
              bitField0_ |= 0x00000010;
              longNames_ = input.readBool();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000020;
              packedStruct_ = input.readBool();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000080;
              skipMessage_ = input.readBool();
              break;
            }
            case 56: {
              int rawValue = input.readEnum();
              fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize value = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(7, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                intSize_ = value;
              }
              break;
            }
            case 64: {
              bitField0_ |= 0x00000100;
              noUnions_ = input.readBool();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000200;
              msgid_ = input.readUInt32();
              break;
            }
            case 80: {
              bitField0_ |= 0x00000040;
              packedEnum_ = input.readBool();
              break;
            }
            case 88: {
              bitField0_ |= 0x00000400;
              anonymousOneof_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
    }

    public static com.google.protobuf.Parser<NanoPBOptions> PARSER =
        new com.google.protobuf.AbstractParser<NanoPBOptions>() {
      public NanoPBOptions parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new NanoPBOptions(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<NanoPBOptions> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int MAX_SIZE_FIELD_NUMBER = 1;
    private int maxSize_;
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    public boolean hasMaxSize() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 max_size = 1;</code>
     *
     * <pre>
     * Allocated size for 'bytes' and 'string' fields.
     * </pre>
     */
    public int getMaxSize() {
      return maxSize_;
    }

    public static final int MAX_COUNT_FIELD_NUMBER = 2;
    private int maxCount_;
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    public boolean hasMaxCount() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 max_count = 2;</code>
     *
     * <pre>
     * Allocated number of entries in arrays ('repeated' fields)
     * </pre>
     */
    public int getMaxCount() {
      return maxCount_;
    }

    public static final int INT_SIZE_FIELD_NUMBER = 7;
    private fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize intSize_;
    /**
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     *
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     */
    public boolean hasIntSize() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
     *
     * <pre>
     * Size of integer fields. Can save some memory if you don't need
     * full 32 bits for the value.
     * </pre>
     */
    public fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize() {
      return intSize_;
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType type_;
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
     *
     * <pre>
     * Force type of field (callback or static allocation)
     * </pre>
     */
    public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
      return type_;
    }

    public static final int LONG_NAMES_FIELD_NUMBER = 4;
    private boolean longNames_;
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    public boolean hasLongNames() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool long_names = 4 [default = true];</code>
     *
     * <pre>
     * Use long names for enums, i.e. EnumName_EnumValue.
     * </pre>
     */
    public boolean getLongNames() {
      return longNames_;
    }

    public static final int PACKED_STRUCT_FIELD_NUMBER = 5;
    private boolean packedStruct_;
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     */
    public boolean hasPackedStruct() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bool packed_struct = 5 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated structs.
     * Note: this cannot be used on CPUs that break on unaligned
     * accesses to variables.
     * </pre>
     */
    public boolean getPackedStruct() {
      return packedStruct_;
    }

    public static final int PACKED_ENUM_FIELD_NUMBER = 10;
    private boolean packedEnum_;
    /**
     * <code>optional bool packed_enum = 10 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     */
    public boolean hasPackedEnum() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool packed_enum = 10 [default = false];</code>
     *
     * <pre>
     * Add 'packed' attribute to generated enums.
     * </pre>
     */
    public boolean getPackedEnum() {
      return packedEnum_;
    }

    public static final int SKIP_MESSAGE_FIELD_NUMBER = 6;
    private boolean skipMessage_;
    /**
     * <code>optional bool skip_message = 6 [default = false];</code>
     *
     * <pre>
     * Skip this message
     * </pre>
     */
    public boolean hasSkipMessage() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bool skip_message = 6 [default = false];</code>
     *
     * <pre>
     * Skip this message
     * </pre>
     */
    public boolean getSkipMessage() {
      return skipMessage_;
    }

    public static final int NO_UNIONS_FIELD_NUMBER = 8;
    private boolean noUnions_;
    /**
     * <code>optional bool no_unions = 8 [default = false];</code>
     *
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     */
    public boolean hasNoUnions() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>optional bool no_unions = 8 [default = false];</code>
     *
     * <pre>
     * Generate oneof fields as normal optional fields instead of union.
     * </pre>
     */
    public boolean getNoUnions() {
      return noUnions_;
    }

    public static final int MSGID_FIELD_NUMBER = 9;
    private int msgid_;
    /**
     * <code>optional uint32 msgid = 9;</code>
     *
     * <pre>
     * integer type tag for a message
     * </pre>
     */
    public boolean hasMsgid() {
      return ((bitField0_ & 0x00000200) == 0x00000200);
    }
    /**
     * <code>optional uint32 msgid = 9;</code>
     *
     * <pre>
     * integer type tag for a message
     * </pre>
     */
    public int getMsgid() {
      return msgid_;
    }

    public static final int ANONYMOUS_ONEOF_FIELD_NUMBER = 11;
    private boolean anonymousOneof_;
    /**
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     *
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     */
    public boolean hasAnonymousOneof() {
      return ((bitField0_ & 0x00000400) == 0x00000400);
    }
    /**
     * <code>optional bool anonymous_oneof = 11 [default = false];</code>
     *
     * <pre>
     * decode oneof as anonymous union
     * </pre>
     */
    public boolean getAnonymousOneof() {
      return anonymousOneof_;
    }

    private void initFields() {
      maxSize_ = 0;
      maxCount_ = 0;
      intSize_ = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT;
      type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
      longNames_ = true;
      packedStruct_ = false;
      packedEnum_ = false;
      skipMessage_ = false;
      noUnions_ = false;
      msgid_ = 0;
      anonymousOneof_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, maxCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeEnum(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(4, longNames_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBool(5, packedStruct_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBool(6, skipMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(7, intSize_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeBool(8, noUnions_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        output.writeUInt32(9, msgid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(10, packedEnum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        output.writeBool(11, anonymousOneof_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, maxSize_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, maxCount_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, longNames_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, packedStruct_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, skipMessage_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, intSize_.getNumber());
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(8, noUnions_);
      }
      if (((bitField0_ & 0x00000200) == 0x00000200)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, msgid_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, packedEnum_);
      }
      if (((bitField0_ & 0x00000400) == 0x00000400)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(11, anonymousOneof_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code NanoPBOptions}
     *
     * <pre>
     * This is the inner options message, which basically defines options for
     * a field. When it is used in message or file scope, it applies to all
     * fields.
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:NanoPBOptions)
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class, fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.Builder.class);
      }

      // Construct using fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        maxSize_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        maxCount_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        intSize_ = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000008);
        longNames_ = true;
        bitField0_ = (bitField0_ & ~0x00000010);
        packedStruct_ = false;
        bitField0_ = (bitField0_ & ~0x00000020);
        packedEnum_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        skipMessage_ = false;
        bitField0_ = (bitField0_ & ~0x00000080);
        noUnions_ = false;
        bitField0_ = (bitField0_ & ~0x00000100);
        msgid_ = 0;
        bitField0_ = (bitField0_ & ~0x00000200);
        anonymousOneof_ = false;
        bitField0_ = (bitField0_ & ~0x00000400);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.internal_static_NanoPBOptions_descriptor;
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions getDefaultInstanceForType() {
        return fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance();
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions build() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions buildPartial() {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions result = new fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.maxSize_ = maxSize_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.maxCount_ = maxCount_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.intSize_ = intSize_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.longNames_ = longNames_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.packedStruct_ = packedStruct_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.packedEnum_ = packedEnum_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.skipMessage_ = skipMessage_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.noUnions_ = noUnions_;
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000200;
        }
        result.msgid_ = msgid_;
        if (((from_bitField0_ & 0x00000400) == 0x00000400)) {
          to_bitField0_ |= 0x00000400;
        }
        result.anonymousOneof_ = anonymousOneof_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) {
          return mergeFrom((fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions other) {
        if (other == fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance()) return this;
        if (other.hasMaxSize()) {
          setMaxSize(other.getMaxSize());
        }
        if (other.hasMaxCount()) {
          setMaxCount(other.getMaxCount());
        }
        if (other.hasIntSize()) {
          setIntSize(other.getIntSize());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasLongNames()) {
          setLongNames(other.getLongNames());
        }
        if (other.hasPackedStruct()) {
          setPackedStruct(other.getPackedStruct());
        }
        if (other.hasPackedEnum()) {
          setPackedEnum(other.getPackedEnum());
        }
        if (other.hasSkipMessage()) {
          setSkipMessage(other.getSkipMessage());
        }
        if (other.hasNoUnions()) {
          setNoUnions(other.getNoUnions());
        }
        if (other.hasMsgid()) {
          setMsgid(other.getMsgid());
        }
        if (other.hasAnonymousOneof()) {
          setAnonymousOneof(other.getAnonymousOneof());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int maxSize_ ;
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public boolean hasMaxSize() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public int getMaxSize() {
        return maxSize_;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public Builder setMaxSize(int value) {
        bitField0_ |= 0x00000001;
        maxSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_size = 1;</code>
       *
       * <pre>
       * Allocated size for 'bytes' and 'string' fields.
       * </pre>
       */
      public Builder clearMaxSize() {
        bitField0_ = (bitField0_ & ~0x00000001);
        maxSize_ = 0;
        onChanged();
        return this;
      }

      private int maxCount_ ;
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public boolean hasMaxCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public int getMaxCount() {
        return maxCount_;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public Builder setMaxCount(int value) {
        bitField0_ |= 0x00000002;
        maxCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 max_count = 2;</code>
       *
       * <pre>
       * Allocated number of entries in arrays ('repeated' fields)
       * </pre>
       */
      public Builder clearMaxCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        maxCount_ = 0;
        onChanged();
        return this;
      }

      private fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize intSize_ = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT;
      /**
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       *
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       */
      public boolean hasIntSize() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       *
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       */
      public fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize getIntSize() {
        return intSize_;
      }
      /**
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       *
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       */
      public Builder setIntSize(fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        intSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .IntSize int_size = 7 [default = IS_DEFAULT];</code>
       *
       * <pre>
       * Size of integer fields. Can save some memory if you don't need
       * full 32 bits for the value.
       * </pre>
       */
      public Builder clearIntSize() {
        bitField0_ = (bitField0_ & ~0x00000004);
        intSize_ = fi.kapsi.koti.jpa.nanopb.Nanopb.IntSize.IS_DEFAULT;
        onChanged();
        return this;
      }

      private fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType getType() {
        return type_;
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public Builder setType(fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .FieldType type = 3 [default = FT_DEFAULT];</code>
       *
       * <pre>
       * Force type of field (callback or static allocation)
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = fi.kapsi.koti.jpa.nanopb.Nanopb.FieldType.FT_DEFAULT;
        onChanged();
        return this;
      }

      private boolean longNames_ = true;
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public boolean hasLongNames() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public boolean getLongNames() {
        return longNames_;
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public Builder setLongNames(boolean value) {
        bitField0_ |= 0x00000010;
        longNames_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool long_names = 4 [default = true];</code>
       *
       * <pre>
       * Use long names for enums, i.e. EnumName_EnumValue.
       * </pre>
       */
      public Builder clearLongNames() {
        bitField0_ = (bitField0_ & ~0x00000010);
        longNames_ = true;
        onChanged();
        return this;
      }

      private boolean packedStruct_ ;
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       */
      public boolean hasPackedStruct() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       */
      public boolean getPackedStruct() {
        return packedStruct_;
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       */
      public Builder setPackedStruct(boolean value) {
        bitField0_ |= 0x00000020;
        packedStruct_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool packed_struct = 5 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated structs.
       * Note: this cannot be used on CPUs that break on unaligned
       * accesses to variables.
       * </pre>
       */
      public Builder clearPackedStruct() {
        bitField0_ = (bitField0_ & ~0x00000020);
        packedStruct_ = false;
        onChanged();
        return this;
      }

      private boolean packedEnum_ ;
      /**
       * <code>optional bool packed_enum = 10 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       */
      public boolean hasPackedEnum() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool packed_enum = 10 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       */
      public boolean getPackedEnum() {
        return packedEnum_;
      }
      /**
       * <code>optional bool packed_enum = 10 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       */
      public Builder setPackedEnum(boolean value) {
        bitField0_ |= 0x00000040;
        packedEnum_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool packed_enum = 10 [default = false];</code>
       *
       * <pre>
       * Add 'packed' attribute to generated enums.
       * </pre>
       */
      public Builder clearPackedEnum() {
        bitField0_ = (bitField0_ & ~0x00000040);
        packedEnum_ = false;
        onChanged();
        return this;
      }

      private boolean skipMessage_ ;
      /**
       * <code>optional bool skip_message = 6 [default = false];</code>
       *
       * <pre>
       * Skip this message
       * </pre>
       */
      public boolean hasSkipMessage() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bool skip_message = 6 [default = false];</code>
       *
       * <pre>
       * Skip this message
       * </pre>
       */
      public boolean getSkipMessage() {
        return skipMessage_;
      }
      /**
       * <code>optional bool skip_message = 6 [default = false];</code>
       *
       * <pre>
       * Skip this message
       * </pre>
       */
      public Builder setSkipMessage(boolean value) {
        bitField0_ |= 0x00000080;
        skipMessage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool skip_message = 6 [default = false];</code>
       *
       * <pre>
       * Skip this message
       * </pre>
       */
      public Builder clearSkipMessage() {
        bitField0_ = (bitField0_ & ~0x00000080);
        skipMessage_ = false;
        onChanged();
        return this;
      }

      private boolean noUnions_ ;
      /**
       * <code>optional bool no_unions = 8 [default = false];</code>
       *
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       */
      public boolean hasNoUnions() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional bool no_unions = 8 [default = false];</code>
       *
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       */
      public boolean getNoUnions() {
        return noUnions_;
      }
      /**
       * <code>optional bool no_unions = 8 [default = false];</code>
       *
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       */
      public Builder setNoUnions(boolean value) {
        bitField0_ |= 0x00000100;
        noUnions_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool no_unions = 8 [default = false];</code>
       *
       * <pre>
       * Generate oneof fields as normal optional fields instead of union.
       * </pre>
       */
      public Builder clearNoUnions() {
        bitField0_ = (bitField0_ & ~0x00000100);
        noUnions_ = false;
        onChanged();
        return this;
      }

      private int msgid_ ;
      /**
       * <code>optional uint32 msgid = 9;</code>
       *
       * <pre>
       * integer type tag for a message
       * </pre>
       */
      public boolean hasMsgid() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional uint32 msgid = 9;</code>
       *
       * <pre>
       * integer type tag for a message
       * </pre>
       */
      public int getMsgid() {
        return msgid_;
      }
      /**
       * <code>optional uint32 msgid = 9;</code>
       *
       * <pre>
       * integer type tag for a message
       * </pre>
       */
      public Builder setMsgid(int value) {
        bitField0_ |= 0x00000200;
        msgid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 msgid = 9;</code>
       *
       * <pre>
       * integer type tag for a message
       * </pre>
       */
      public Builder clearMsgid() {
        bitField0_ = (bitField0_ & ~0x00000200);
        msgid_ = 0;
        onChanged();
        return this;
      }

      private boolean anonymousOneof_ ;
      /**
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       *
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       */
      public boolean hasAnonymousOneof() {
        return ((bitField0_ & 0x00000400) == 0x00000400);
      }
      /**
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       *
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       */
      public boolean getAnonymousOneof() {
        return anonymousOneof_;
      }
      /**
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       *
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       */
      public Builder setAnonymousOneof(boolean value) {
        bitField0_ |= 0x00000400;
        anonymousOneof_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool anonymous_oneof = 11 [default = false];</code>
       *
       * <pre>
       * decode oneof as anonymous union
       * </pre>
       */
      public Builder clearAnonymousOneof() {
        bitField0_ = (bitField0_ & ~0x00000400);
        anonymousOneof_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:NanoPBOptions)
    }

    static {
      defaultInstance = new NanoPBOptions(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:NanoPBOptions)
  }

  public static final int NANOPB_FILEOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FileOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FileOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbFileopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_MSGOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.MessageOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.MessageOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbMsgopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_ENUMOPT_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.EnumOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.EnumOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopbEnumopt = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  public static final int NANOPB_FIELD_NUMBER = 1010;
  /**
   * <code>extend .google.protobuf.FieldOptions { ... }</code>
   */
  public static final
    com.google.protobuf.GeneratedMessage.GeneratedExtension<
      com.google.protobuf.DescriptorProtos.FieldOptions,
      fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions> nanopb = com.google.protobuf.GeneratedMessage
          .newFileScopedGeneratedExtension(
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.class,
        fi.kapsi.koti.jpa.nanopb.Nanopb.NanoPBOptions.getDefaultInstance());
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_NanoPBOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_NanoPBOptions_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014nanopb.proto\032 google/protobuf/descript" +
      "or.proto\"\274\002\n\rNanoPBOptions\022\020\n\010max_size\030\001" +
      " \001(\005\022\021\n\tmax_count\030\002 \001(\005\022&\n\010int_size\030\007 \001(" +
      "\0162\010.IntSize:\nIS_DEFAULT\022$\n\004type\030\003 \001(\0162\n." +
      "FieldType:\nFT_DEFAULT\022\030\n\nlong_names\030\004 \001(" +
      "\010:\004true\022\034\n\rpacked_struct\030\005 \001(\010:\005false\022\032\n" +
      "\013packed_enum\030\n \001(\010:\005false\022\033\n\014skip_messag" +
      "e\030\006 \001(\010:\005false\022\030\n\tno_unions\030\010 \001(\010:\005false" +
      "\022\r\n\005msgid\030\t \001(\r\022\036\n\017anonymous_oneof\030\013 \001(\010" +
      ":\005false*Z\n\tFieldType\022\016\n\nFT_DEFAULT\020\000\022\017\n\013",
      "FT_CALLBACK\020\001\022\016\n\nFT_POINTER\020\004\022\r\n\tFT_STAT" +
      "IC\020\002\022\r\n\tFT_IGNORE\020\003*D\n\007IntSize\022\016\n\nIS_DEF" +
      "AULT\020\000\022\010\n\004IS_8\020\010\022\t\n\005IS_16\020\020\022\t\n\005IS_32\020 \022\t" +
      "\n\005IS_64\020@:E\n\016nanopb_fileopt\022\034.google.pro" +
      "tobuf.FileOptions\030\362\007 \001(\0132\016.NanoPBOptions" +
      ":G\n\rnanopb_msgopt\022\037.google.protobuf.Mess" +
      "ageOptions\030\362\007 \001(\0132\016.NanoPBOptions:E\n\016nan" +
      "opb_enumopt\022\034.google.protobuf.EnumOption" +
      "s\030\362\007 \001(\0132\016.NanoPBOptions:>\n\006nanopb\022\035.goo" +
      "gle.protobuf.FieldOptions\030\362\007 \001(\0132\016.NanoP",
      "BOptionsB\032\n\030fi.kapsi.koti.jpa.nanopb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.DescriptorProtos.getDescriptor(),
        }, assigner);
    internal_static_NanoPBOptions_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_NanoPBOptions_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_NanoPBOptions_descriptor,
        new java.lang.String[] { "MaxSize", "MaxCount", "IntSize", "Type", "LongNames", "PackedStruct", "PackedEnum", "SkipMessage", "NoUnions", "Msgid", "AnonymousOneof", });
    nanopbFileopt.internalInit(descriptor.getExtensions().get(0));
    nanopbMsgopt.internalInit(descriptor.getExtensions().get(1));
    nanopbEnumopt.internalInit(descriptor.getExtensions().get(2));
    nanopb.internalInit(descriptor.getExtensions().get(3));
    com.google.protobuf.DescriptorProtos.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
