/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.5 at Thu Apr 07 21:22:22 2016. */

#ifndef PB_DEVICECOMMANDS_PB_H_INCLUDED
#define PB_DEVICECOMMANDS_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _device_commands_Person_PhoneType {
    device_commands_Person_PhoneType_MOBILE = 0,
    device_commands_Person_PhoneType_HOME = 1,
    device_commands_Person_PhoneType_WORK = 2
} device_commands_Person_PhoneType;

/* Struct definitions */
typedef struct _device_commands_AddressBook {
    pb_callback_t person;
/* @@protoc_insertion_point(struct:device_commands_AddressBook) */
} device_commands_AddressBook;

typedef struct _device_commands_Person {
    pb_callback_t name;
    int32_t id;
    pb_callback_t email;
    pb_callback_t phone;
/* @@protoc_insertion_point(struct:device_commands_Person) */
} device_commands_Person;

typedef struct _device_commands_Person_PhoneNumber {
    pb_callback_t number;
    bool has_type;
    device_commands_Person_PhoneType type;
/* @@protoc_insertion_point(struct:device_commands_Person_PhoneNumber) */
} device_commands_Person_PhoneNumber;

/* Default values for struct fields */
extern const device_commands_Person_PhoneType device_commands_Person_PhoneNumber_type_default;

/* Initializer values for message structs */
#define device_commands_Person_init_default      {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define device_commands_Person_PhoneNumber_init_default {{{NULL}, NULL}, false, device_commands_Person_PhoneType_HOME}
#define device_commands_AddressBook_init_default {{{NULL}, NULL}}
#define device_commands_Person_init_zero         {{{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define device_commands_Person_PhoneNumber_init_zero {{{NULL}, NULL}, false, (device_commands_Person_PhoneType)0}
#define device_commands_AddressBook_init_zero    {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define device_commands_AddressBook_person_tag   1
#define device_commands_Person_name_tag          1
#define device_commands_Person_id_tag            2
#define device_commands_Person_email_tag         3
#define device_commands_Person_phone_tag         4
#define device_commands_Person_PhoneNumber_number_tag 1
#define device_commands_Person_PhoneNumber_type_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t device_commands_Person_fields[5];
extern const pb_field_t device_commands_Person_PhoneNumber_fields[3];
extern const pb_field_t device_commands_AddressBook_fields[2];

/* Maximum encoded size of messages (where known) */

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define DEVICECOMMANDS_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
