/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.5 at Thu Apr 07 21:22:22 2016. */

#include "DeviceCommands.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

const device_commands_Person_PhoneType device_commands_Person_PhoneNumber_type_default = device_commands_Person_PhoneType_HOME;


const pb_field_t device_commands_Person_fields[5] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, device_commands_Person, name, name, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, device_commands_Person, id, name, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, device_commands_Person, email, id, 0),
    PB_FIELD(  4, MESSAGE , REPEATED, CALLBACK, OTHER, device_commands_Person, phone, email, &device_commands_Person_PhoneNumber_fields),
    PB_LAST_FIELD
};

const pb_field_t device_commands_Person_PhoneNumber_fields[3] = {
    PB_FIELD(  1, STRING  , REQUIRED, CALLBACK, FIRST, device_commands_Person_PhoneNumber, number, number, 0),
    PB_FIELD(  2, UENUM   , OPTIONAL, STATIC  , OTHER, device_commands_Person_PhoneNumber, type, number, &device_commands_Person_PhoneNumber_type_default),
    PB_LAST_FIELD
};

const pb_field_t device_commands_AddressBook_fields[2] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, device_commands_AddressBook, person, person, &device_commands_Person_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(device_commands_Person, phone) < 65536 && pb_membersize(device_commands_AddressBook, person) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_device_commands_Person_device_commands_Person_PhoneNumber_device_commands_AddressBook)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(device_commands_Person, phone) < 256 && pb_membersize(device_commands_AddressBook, person) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_device_commands_Person_device_commands_Person_PhoneNumber_device_commands_AddressBook)
#endif


/* @@protoc_insertion_point(eof) */
